name: Node CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: estree-to-babel
    strategy:
      matrix:
        node-version:
          - 20.x
          - 22.x
          - 23.x
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: bun i redrun -g --no-save
      - name: Install
        run: bun i -f --no-save
      - name: Lint
        run: redrun fix:lint
      - name: Commit fixes
        continue-on-error: true
        uses: EndBug/add-and-commit@v9
        with:
          fetch: --force
          message: "chore: ${{ env.NAME }}: actions: lint ☘️"
          pull: --rebase --autostash
      - name: Coverage
        run: redrun coverage report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
